import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col max-w-5xl mx-auto">
        <header>Header</header>
        <main className="flex-1 my-12">{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  )
}
